<!-- Begin Footer -->
<br /><br />
<div align="center">
    <div align="center" style="border:dashed 1px #999; width:80%;">
        <p style="font-size:xx-small">
        	&copy; Big Brothers Big Sisters Greater Fredericksburg
        	<br>
        	. 325 Wallace St #A, Fredericksburg, VA 22401
        	<br>
        	Phone: 540-371-7444&nbsp;&nbsp;&nbsp;&nbsp;Email: 
        	info@bbbsfred.org
        </p>
    </div>
</div>
<!-- End Footer -->
