<!-- Begin Footer -->
<br /><br />
<div align="center">
    <div align="center" style="border:dashed 1px #999; width:80%;">

        <p style="font-size:xx-small">Copyright &copy; 2008-2015 by Jerrick Hoang, Ivy Xing, Sam Roberts, James Cook, 
        Johnny Coster, Judy Yang, Jackson Moniaga, Oliver Radwan, Maxwell Palmer, Nolan McNair, Taylor Talmage, and <a href="mailto:allen@npfi.org>">Allen Tucker</a>.  
            <i>Homebase</i> was developed at Bowdoin College for the Ronald McDonald Houses in Maine.  It is free open source software and it comes with absolutely no warranty.  
            You can redistribute and/or modify this software under the terms of the
            <a href="http://www.gnu.org/licenses/gpl.html"> GNU General Public License</a>.
        </p>
    </div>
</div>
<!-- End Footer -->