<div class="infoform">
	<h1>
		Little Application
	</h1>
	<form method="POST">
		<label for="adult_name">Parent/Guardian</label>
		<input type="text" name="adult_name"/><br/>
		<label for="relation">Relationship to child</label>
		<input type="text" name="relation"/><br/>
		<label for="legal_custody">Do you have legal custody of the child?</label>
		<input type="checkbox" name="legal_custody"><br>
		<label for="share_custody">Is there a person who shares legal custody of this child?</label>
		<input type="checkbox" name="share_custody"/><br/>
	</form>
</div>